public class Player {
    public void Player() {
        String Player1Name = 'jalen Green';
        String Player2Name = 'jabarismith';
        String Player3Name = 'Alperen Sengul';
        String Player4Name = 'kevin porter';
        String Player5Name = 'Eric Gordon';

        system.debug(Player1Name);
        system.debug(Player2Name);
        system.debug(Player3Name);
        system.debug(Player4Name);
        system.debug(Player5Name);
        

    }
}